markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

author: Akash Kothawale
project: Facebook on Terminal
fulldescription: Access Facebook on Terminal
url: decached.com
description: Hi, I'm Akash Kothawale. I live in Pune, Maharashtra, India. I'm @decached on most services.
email: io@decached.com
githuburl: https://github.com/decached/fbterminal
